---
baseurl: "https://tokio.rs"
title: "Tokio - The asynchronous run-time for the Rust programming language."
languageCode: "en-us"
canonifyURLs: "true"
googleAnalytics: "UA-90234741-1"

menu:
  docs:
    - identifier: "getting_started"
      name: "Getting started"
      weight: 1000
    - identifier: "futures"
      name: "[0.1] Working with futures"
      weight: 2000
    - identifier: "io"
      name: "[0.1] I/O with Tokio"
      weight: 3000
    - identifier: "going_deeper"
      name: "Going deeper"
      weight: 7000
    - identifier: "internals"
      name: "[0.1] Tokio internals"
      weight: 8000
    - identifier: "reference"
      name: "API documentation"
      url: "https://docs.rs/tokio"
      weight: 9000


params:
  tokioDocsURL: "https://docs.rs/tokio/0.1/tokio"
  tokioExecutorDocsURL: "https://docs.rs/tokio-executor/0.1/tokio_executor"
  tokioIoDocsURL: "https://docs.rs/tokio-io/0.1/tokio_io"
  tokioCodecDocsURL: "https://docs.rs/tokio-codec/0.1/tokio_codec"
  tokioReactorDocsURL: "https://tokio-rs.github.io/tokio/tokio_reactor/"
  tokioTimerDocsURL: "https://docs.rs/tokio-timer/0.2"
  futuresDocsURL: "https://docs.rs/futures/0.3/futures"
  futures01DocsURL: "https://docs.rs/futures/0.1/futures"
  mioDocsURL: "https://docs.rs/mio/*/mio"
  coreDocsURL: "https://docs.rs/tokio-core/0.1/tokio_core"
  protoDocsURL: "https://tokio-rs.github.io/tokio-proto/tokio_proto"
  serviceDocsURL: "https://tokio-rs.github.io/tokio-service/tokio_service"
  bytesDocsURL: "https://docs.rs/bytes/0.4/bytes"
  stdDocsURL: "https://doc.rust-lang.org/std"
